name: 🙏 Feature request
description: Suggest an idea for this project
title: "[ENHANCEMENT] <title>"
labels: ["enhancement", "triage"]
assignees:
  - mike-fabian
body:
- type: markdown
  attributes:
    value: "Please choose a useful title to identify your issue."
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe
    description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe the solution you’d like
    description: A clear and concise description of what you want to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe alternatives you’ve considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
